spring:
  application:
    name: SprinklerService
  profiles:
    active: dev

  datasource:
    name: sprinkler
    url: jdbc:h2:mem:sprinkler;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
