server:
  port: 8083

spring:
  application:
    name: sprinkler-service
  profiles:
    active: dev
  config:
    import: configserver:http://config-server:8071

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-server:9092
          auto-create-topics: true
          auto-add-partitions: true
        bindings:
          sprinklerEventSupplier-out-0:
            producer:
              sync: true
      bindings:
        sprinklerEventSupplier-out-0:
          destination: sprinkler-event-topic
      output-bindings: sprinklerEventSupplier-out-0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smarthomehub
          jwk-set-uri: http://keycloak:8080/realms/smarthomehub/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/smarthomehub
        registration:
          keycloak:
            client-name: sprinkler-service
            client-id: sprinkler-service
            authorization-grant-type: authorization_code
            client-secret: LupcWMGyTzWUrKIBTeXv6hbRNuSFXHqQ
            scope:
              - openid
              - offline_access
              - profile
              - roles

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      failureRateThreshold: 20
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  #      ignoreExceptions:
  instances:
    notificationCB:
      baseConfig: default