services:
  config-server:
    build:
      context: ../config-server
    container_name: config-server
    environment:
      SERVER_PORT: 8071
    ports:
      - 8071:8071

  sprinkler-service:
    build:
      context: ../SprinklerService
    container_name: sprinkler-service
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    restart: on-failure
    depends_on:
      - config-server
      - db-dev
      - db-prod
    ports:
      - 8080:8080

  db-dev:
    image: postgres
    container_name: db-dev
    restart: always
    environment:
      POSTGRES_DB: sprinkler_dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - 5432:5432

  db-prod:
    image: postgres
    container_name: db-prod
    restart: always
    environment:
      POSTGRES_DB: sprinkler_prod
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - 5433:5432